version: "3.9"

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=baho
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=mydb
    networks:
      - sqli
    expose:
      - 5432

  backend:
    image: koixo/sqli_backend
    environment:
      - DB_SOURCE=postgresql://baho:secret@postgres:5432/mydb?sslmode=disable
    depends_on:
      - postgres
    volumes:
      - backend:/app
    restart: always
    networks:
      - sqli

  frontend:
    image: koixo/sqli_frontend
    restart: always
    networks:
      - sqli

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - backend
      - frontend
    networks:
      - sqli
    restart: always

volumes:
  backend:

networks:
  sqli:
