version: '3.8'

services:
  backend:
    #build:
     # context: ./jwt-ctf-backend
     # dockerfile: Dockerfile
    image: amahird/backend.dizci.ctf
    expose:
      - 7106
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: unless-stopped
    networks:
      - jwt-amd

  frontend:
    image: amahird/frontend.dizci.ctf
    expose:
      - 80
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - jwt-amd

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - frontend
      - backend
    networks:
      - jwt-amd

networks:
  jwt-amd:

